= Outlook Privacy Plugin

A GnuPG/GPG/OpenPGP encryption plugin for Outlook 2010 and 2013.  Supports both 32 and 64bit versions of Outlook.

== About

This plugin is a fork of the popular Outlook Privacy Plugin by Michael Eddington. It was forked in April 2015 as a students project.

Outlook Privacy Plugin is a security extension for Outlook. It enables Outlook to send and receive email messages that are encrypted and/or signed with the OpenPGP standard. It uses your existing GnuPG/GPG keyrings.

=== 1. Download

Download the installer for the final version of the project at the https://github.com/GPGatHGB/OutlookPrivacyPlugin/releases[releases] page or the most up-to-date version by Michael Eddington https://github.com/dejavusecurity/OutlookPrivacyPlugin[here].

=== 2. Install Gpg4win

Install http://www.gpg4win.org/[gpg4win] and import or create keys as needed. Verify you can see all expected keys from the gpg4win key manager software.

Gpg4win is not required, but highly recommended.

=== 3. Install Outlook Privacy Plugin

Close outlook and run the Outlook Privacy Plugin installer. 

=== 4. Setting custom keyring location (OPTIONAL)

Outlook Privacy Plugin should automatically find your keyrings. However, if they are located in a non-standard location or gpg4win is not being used, a custom location for keyrings can be set via the +GNUPGHOME+ environmental variable. After setting the environmental variable, Outlook must be restarted.

== Features

 * Microsoft Outlook 2010 and 2013
 * Support for both 32bit & 64bit versions of Office
 * Encrypt and decrypt email using OpenPGP standard
 * Supports encrypted attachments
 * Supports multiple recipients
 * Decrypts PGP/MIME
 * Decrypts OpenPGP blocks in HTML email
 * Decrypts HTML emails
 * Multiple email accounts (based on sender/receiver email)
 * Attach public key to emails
 
== Not Supported:

 * Sending PGP/MIME emails
 * Sending HTML email
 * Decrypting in preview pain
 

